# Generated by Django 3.1.3 on 2020-11-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0004_auto_20201122_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='profile',
        ),
    ]
